samples: config/samples.csv

# # Optional parameters
# params:
#   bowtie2:
#     # Optional parameters for bowtie2-build
#     build: ""
#     # Optional parameters for bowtie2-align
#     align: ""
#   sambamba:
#     # Optional parameters for sambamba view
#     view: "--format 'bam' --filter 'mapping_quality >= 30 and not (unmapped or mate_is_unmapped)' "
#     # Optional parameters for sambamba markdup
#     markdup: "--remove-duplicates"
#   picard:
#     # Mapping QC optional parameters
#     metrics: ""

# Optional path to a `genome.csv` file
# genomes: genome.csv

# Internal use only, not described in documentation.
# deactivate import of fair_genome_indexer pipeline.
# Requires the file `genome.csv` to be filled.
# load_fair_genome_indexer: true