samples: config/samples.csv


# Optional path to a `genome.csv` file
genomes: config/genomes.csv

# Internal use only, not described in documentation.
# deactivate import of fair_genome_indexer pipeline.
# Requires the file `genome.csv` to be filled.
# load_fair_genome_indexer: true
# Deactivate the import of fair_fastqc_multiqc pipeline.
# Requires to redefine fastqc and multiqc rules.
# load_fair_fastqc_multiqc: true

# # Avoid git fetching
# fair_genome_indexer_snakefile: /media/tdayris/Dev/fair_genome_indexer/workflow/Snakefile
# fair_fastqc_multiqc_snakefile: /media/tdayris/Dev/fair_fastqc_multiqc/workflow/Snakefile
