$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object


genomes:
  type: string
  description: Path to the CSV file defining genome properties


load_fair_genome_indexer:
  type: boolean
  description: Load (or not) the fair_genome_indexer pipeline. Internal use only.
  default: true


load_fair_fastqc_multiqc:
  type: boolean
  description: Load (or not) the fair_fastqc_multiqc pipeline. Internal use only.
  default: true


samples:
  type: string
  description: Path to the CSV file defining samples and their corresponding fastq paths

params:
  type: object
  description: Optional parameters for each (sub) pipelines used

  # This pipeline supports the exact parameters provided in these documentation
  # fair_genome_indexer: see https://github.com/tdayris/fair_genome_indexer/blob/main/workflow/schemas/config.schema.yaml
  # fair_fastqc_multiqc: see https://github.com/tdayris/fair_fastqc_multiqc/blob/main/workflow/schemas/config.schema.yaml
  # Note: Do not change the pipeline name in the parameteres. 
  # Leave fair_fastqc_multiqc or fair_genome_indexer
  # as they are written in their original configuration file.
  # This is used to disambiguate many parameters.

  fair_bowtie2_mapping:
    type: object
    description: Optional parameters for this pipeline

    bowtie2:
      type: object
      description: Optional parameters for bowtie2
      build:
        type: string
        description: Optional parameters for bowtie2-build
        default: ""

      align:
        type: string
        description: Optional parameters for bowtie2-align


    sambamba:
      type: object
      description: Optional parameters for sambamba
      view:
        type: string
        description: Optional parameters for sambamba view filters
        default: "--format 'bam' --filter 'mapping_quality >= 30 and not (unmapped or mate_is_unmapped)'"
      
      markdup:
        type: string
        description: Optional parameters for sambamba markdup
        default: "--remove-duplicates --overflow-list-size=500000"

    multiqc:
      type: string
      description: Optional parameters for MultiQC

    picard:
      type: object
      metrics:
        type: string
        description: Optional parameters for Picard CollectMultipleMetrics
        default: ""

    samtools:
      type: object
      description: Optional parameters for Samtools
      stats:
        type: string
        description: Optional parameters for Samtools stats quality control
        default: ""

      faidx:
        type: string
        description: Optional parameters for indexing BAMs
        default: ""
   
    ngsderive:
      type: object
      description: Optional parameters for NGSDerive quality controls
      strandedness:
        type: string
        description: Optional parameters for NGSDerive strandedness
        default: ""

      encoding:
        type: string
        description: Optional parameters for NGSDerive encoding
        default: ""

      instrument:
        type: string
        description: Optional parameters for NGSDerive instrument
        default: ""

      readlen:
        type: string
        description: Optional parameters for NGSDerive readlen
        default: ""

    fastp:
      type: object
      descrition: Optional parameters for Fastp's Snakemake-Wrapper
      adapters:
        type: string
        description: Optional adapter given through command line
        default: none

      extra:
        type: string
        description: Optional command line parameters
        default: "--verbose --overrepresentation_analysis"

    goleft:
      type: object
      description: Optional parameters for Goleft quality control
      indexcov:
        type: string
        description: Optional parameters for `indexcov` subcommand
        default: ""

    multiqc:
      type: object
      description: Optional parameters for MultiQC's Snakemake-wrapper
      extra:
        type: string
        description: Optional parameters for MultiQC command line
        default: "--verbose --no-megaqc-upload --no-ansi --force"
      use_input_files_only:
        type: boolean
        description: Use exact list of files or search in directories
        default: true
    
    ucsc:
      type: object
      description: Optional parameters for ucsc tools

      genepred2bed:
        type: string
        description: Optional parameters for genePred to BED conversion
        default: ""

    rseqc:
      type: object
      description: Optional for RSeQC quality controls

      bamstat:
        type: string
        description: Optional parameters for RSeQC bamstat
        default: ""

      read_gc:
        type: string
        description: Optional parameters for RSeQC read_gc
        default: ""

      read_distribution:
        type: string
        description: Optional parameters for RSeQC read_distribution
        default: ""

      inner_distance:
        type: string
        description: Optional parameters for RSeQC inner_distance
        default: ""
