$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object


genomes:
  type: string
  description: Path to the CSV file defining genome properties


samples:
  type: string
  description: Path to the CSV file defining samples and their corresponding fastq paths

params:
  type: object
  bowtie2:
    type: object
    description: Optional parameters for bowtie2
    build:
      type: string
      description: Optional parameters for bowtie2-build
    align:
      type: string
      description: Optional parameters for bowtie2-align


  sambamba:
    type: object
    description: Optional parameters for sambamba
    view:
      type: string
      description: Optional parameters for sambamba view filters
    markdup:
      type: string
      description: Optional parameters for sambamba markdup

required:
  - samples