$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object


genomes:
  type: string
  description: Path to the CSV file defining genome properties


load_fair_genome_indexer:
  type: boolean
  description: Load (or not) the fair_genome_indexer pipeline


samples:
  type: string
  description: Path to the CSV file defining samples and their corresponding fastq paths

params:
  type: object
  bowtie2:
    type: object
    description: Optional parameters for bowtie2
    build:
      type: string
      description: Optional parameters for bowtie2-build
    align:
      type: string
      description: Optional parameters for bowtie2-align


  sambamba:
    type: object
    description: Optional parameters for sambamba
    view:
      type: string
      description: Optional parameters for sambamba view filters
    markdup:
      type: string
      description: Optional parameters for sambamba markdup

  fastqc:
    type: string
    description: Optional parameters for FastQC
  multiqc:
    type: string
    description: Optional parameters for MultiQC

  picard:
    type: object
    metrics:
      type: string
      description: Optional parameters for Picard CollectMultipleMetrics

  samtools:
    type: string
    description: Optional parameters for Samtools stats

  fastp:
    type: object
    adapters:
      type: string
      description: Optional adapter given through command line
    extra:
      type: string
      description: Optional command line parameters

  multiqc:
    typre: string
    description: Optional MultiQC command line parameters

required:
  - samples